server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: destiny-2-data
  jackson:
    mapper:
      accept-case-insensitive-enums: true

bungie:
  client:
    bungie-platform:
      base-url: 'https://www.bungie.net/Platform'
      x-api-key: '${BUNGIE_API_KEY}'
    bungie-common:
      base-url: 'https://www.bungie.net'
